export { default as DashboardIcon } from './dashboard.svg'
export { default as MinistryIcon } from './ministry.svg'
export { default as PrivateDeptIcon } from './private-departments.svg'
export { default as RegionalIcon } from './regional-branches.svg'
export { default as KindergartenIcon } from './kindergartens.svg'
export { default as SchoolIcon } from './schools.svg'
export { default as NationalOrgIcon } from './national-organizations.svg'
export { default as UniversityIcon } from './universities.svg'
export { default as OthersIcon } from './others.svg'
export { default as LogoutIcon } from './logout-icon.svg'

// Dashboard
export { default as TodayApplicationsIcon } from './today-applications.svg'
export { default as TotalApplicationsIcon } from './total-applications.svg'
export { default as ResolvedApplicationsIcon } from './resolved-applications.svg'
export { default as InProcessApplicationsIcon } from './in-process-applications.svg'
export { default as RejectedApplicationsIcon } from './rejected-applications.svg'
export { default as ListIcon } from './list-icon.svg'
